### ISSUE TITLE
The text generates fine, but audio generation encountered the following error:

### ISSUE THREAD

**Issue by webdada** [agituts/gemini-2-podcast#1]
(venv) macbook@MacBooks-MacBook-Pro gemini-2-podcast % python3 generate_podcast.py
Generating podcast script...
Enter source type (pdf/url/txt/md) or 'done' to finish: pdf
Enter PDF file path: ./2020Scrum.pdf
Enter source type (pdf/url/txt/md) or 'done' to finish: done
Podcast script saved successfully!
Script generated at podcast_script.txt. Press Enter to proceed to audio generation or 'q' to quit: 
Converting script to audio...
Connection closed: received 1011 (internal error) Request trace id: 7a63af47bb8f736a, Quota exceeded for quota metric 'Bidi generate content active sessions' and limit 'Bidi; then sent 1011 (internal error) Request trace id: 7a63af47bb8f736a, Quota exceeded for quota metric 'Bidi generate content active sessions' and limit 'Bidi
  + Exception Group Traceback (most recent call last):
  |   File "/Users/macbook/dev/gemini-2-podcast/generate_audio.py", line 152, in <module>
  |     asyncio.run(main())
  |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/Users/macbook/dev/gemini-2-podcast/generate_audio.py", line 136, in main
  |     async with asyncio.TaskGroup() as tg:
  |                ^^^^^^^^^^^^^^^^^^^
  |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/taskgroups.py", line 71, in __aexit__
  |     return await self._aexit(et, exc)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/taskgroups.py", line 164, in _aexit
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/Users/macbook/dev/gemini-2-podcast/generate_audio.py", line 91, in process_speaker_concurrent
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/taskgroups.py", line 71, in __aexit__
    |     return await self._aexit(et, exc)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/taskgroups.py", line 164, in _aexit
    |     raise BaseExceptionGroup(
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/Users/macbook/dev/gemini-2-podcast/audio_processor.py", line 57, in process_batch
      |     await self.receive_audio(output_file)
      |   File "/Users/macbook/dev/gemini-2-podcast/audio_processor.py", line 96, in receive_audio
      |     async for raw_response in self.ws:
      |   File "/Users/macbook/dev/gemini-2-podcast/venv/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 242, in __aiter__
      |     yield await self.recv()
      |           ^^^^^^^^^^^^^^^^^
      |   File "/Users/macbook/dev/gemini-2-podcast/venv/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 313, in recv
      |     raise self.protocol.close_exc from self.recv_exc
      | websockets.exceptions.ConnectionClosedError: received 1011 (internal error) Request trace id: 7a63af47bb8f736a, Quota exceeded for quota metric 'Bidi generate content active sessions' and limit 'Bidi; then sent 1011 (internal error) Request trace id: 7a63af47bb8f736a, Quota exceeded for quota metric 'Bidi generate content active sessions' and limit 'Bidi
      +------------------------------------
Process failed: Command '['/Users/macbook/dev/gemini-2-podcast/venv/bin/python3', 'generate_audio.py']' returned non-zero exit status 1.

**Comment by agituts** [comment]
Either the podcast script generates audio that is greater than 15 minutes, or you have used up the entire limit of your current Google API. Try using a different API.

**Comment by agituts** [comment]
Please check now; I've updated a couple of files to improve session handling. It should now support up to 30 minutes of audio without an issue.
