### ISSUE TITLE
 output from running the README.md through it - audio dialog output buggy 

### ISSUE THREAD

**Issue by teebu** [agituts/gemini-2-podcast#3]
It went well first, at the end it started going into a weird loop for a while. The audio generation has a bug.

It starts using Speaker A and Speaker B for same lines.

[podcast_script.txt](https://github.com/user-attachments/files/18268433/podcast_script.txt)

Not sure the best place to share final_podcast.wav, github doesn't allow wav files: https://file.io/hT820oB0GTpB

Side note, comparing to actual notebookLM output i'd say your prompt could use more tweaking, there: https://file.io/tQFuQgiumJWW

I suggest adding tests.

**Comment by agituts** [comment]
Please check now; I’ve updated the generate_audio.py file. It should now produce the audio correctly. Ensure that you clone the repo again!
